=== openc/openc-schema/schemas/includes/subsequent-registration.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "A representation of entity registration changing over time",
  "type": "object",
  "properties": {
    "data_type": {
      "enum": [
        "subsequent_registration"
      ]
    },
    "previous_entity": {
      "description": "the predecessor entity",
      "$ref": "entity.json"
    },
    "subsequent_entity": {
      "description": "the successor entity",
      "$ref": "entity.json"
    },
    "subsequent_registration_start_date": {
      "description": "date when subsequent registration started",
      "type": "string",
      "format": "date"
    },
    "previous_registration_end_date": {
      "description": "date when previous registration ended",
      "type": "string",
      "format": "date"
    },
    "start_date": {
      "description": "date when subsequent registration was valid from",
      "type": "string",
      "format": "date"
    },
    "start_date_type": {
      "enum": [
        "at",
        "before",
        "after"
      ]
    },
    "sample_date": {
      "description": "date when subsequent registration was sampled",
      "type": "string",
      "format": "date"
    },
    "retrieved_at": {
      "description": "date when subsequent registration was retrieved",
      "type": "string",
      "format": "date"
    },
    "source_url": {
      "description": "URL of the source of the data (e.g. download URL), or if there is not persistent URL the page from which it can be found (e.g. search page)",
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": [
    "data_type",
    "previous_entity",
    "subsequent_entity"
  ],
  "anyOf": [
    {
      "required": [
        "start_date"
      ]
    },
    {
      "required": [
        "sample_date"
      ]
    },
    {
      "required": [
        "retrieved_at"
      ]
    }
  ]
}

=== openc/openc-schema/spec/sample-data/valid/includes/subsequent-registration-01.json
{
  "data_type": "subsequent_registration",
  "previous_entity": {
    "entity_properties": {
      "name": "Vorsprung",
      "company_number": "R111_HRB123",
      "jurisdiction_code": "de"
    },
    "entity_type": "company"
  },
  "subsequent_entity": {
    "entity_properties": {
      "name": "Teknik",
      "company_number": "R222_HRB999",
      "jurisdiction_code": "de"
    },
    "entity_type": "company"
  },
  "source_url": "https://www.foo.com?bar=123",
  "start_date": "2018-05-01"
}
