=== openc/openc-schema/schemas/company-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "A company in OpenCorporates",
  "type": "object",
  "properties": {
    "company_number": {
      "type": "string",
      "description": "unique identifier given by the corporate register with which it is incorporated",
      "minLength": 1
    },
    "name": {
      "type": "string",
      "description": "Legal name of the company",
      "minLength": 1
    },
    "jurisdiction_code": {
      "type": "string",
      "description": "Code representing the jurisdiction/company register which is the canonical record of the companyâ€™s existence. Uses underscored ISO 3166-2 to represent it, e.g. es for Spain, us_de for Delaware",
      "minLength": 2,
      "maxLength": 5
    },
    "incorporation_date": {
      "format": "date"
    },
    "dissolution_date": {
      "format": "date"
    },
    "retrieved_at": {
      "format": "date-time"
    },
    "current_status": {
      "type": "string"
    },
    "company_type": {
      "type": "string"
    },
    "registry_url": {
      "type": "string"
    },
    "website": {
      "type": "string",
      "minLength": 5
    },
    "telephone_number": {
      "type": "string",
      "minLength": 4
    },
    "fax_number": {
      "type": "string",
      "minLength": 4
    },
    "registered_address": {
      "$ref": "includes/address.json"
    },
    "headquarters_address": {
      "$ref": "includes/address.json"
    },
    "mailing_address": {
      "$ref": "includes/address.json"
    },
    "officers": {
      "type": "array",
      "items": {
        "$ref": "includes/officer.json"
      }
    },
    "share_parcels": {
      "type": "array",
      "items": {
        "$ref": "includes/share-parcel.json"
      }
    },
    "total_shares": {
      "$ref": "includes/total-shares.json"
    },
    "filings": {
      "type": "array",
      "items": {
        "$ref": "includes/filing.json"
      }
    },
    "industry_codes": {
      "type": "array",
      "items": {
        "$ref": "includes/industry_code.json"
      }
    },
    "previous_names": {
      "type": "array",
      "items": {
        "$ref": "includes/previous_name.json"
      }
    },
    "alternative_names": {
      "type": "array",
      "items": {
        "$ref": "includes/alternative_name.json"
      }
    },
    "branch": {
      "type": ["string","null"],
      "description": "A flag to denote whether a company is a branch entity. This should only be set if the company is a type of branch (otherwise should be null). In general the only option here is 'F' for a 'Foreign' branch, i.e. an out-of-jurisdiction entity that has registered as having a presence in the jurisdiction. In the US this is sometimes called a Foreign Corporation",
      "enum": ["F", "L",null]
    },
    "all_attributes": {
      "type": "object",
      "description": "Other arbitrary attributes for a given company",
      "properties": {
        "jurisdiction_of_origin": {
          "type": ["string","null"],
          "description": "The jurisdiction of the 'home' company if this is a branch",
          "minLength": 1
        },
        "home_company_number": {
          "type": ["string","null"],
          "description": "If the entity is a 'branch', this is the company_number of the 'home' company in the home company's jurisdiction",
          "minLength": 1
        },
        "home_legal_name": {
          "type": ["string","null"],
          "description": "The legal name of the 'home' company in its jurisdiction if this is a branch, and the name is different from the legal name of the branch",
          "minLength": 1
        },
        "registered_agent_address": {
          "type": ["string","null"],
          "description": "The address of the 'Agent', a public address to which legal papers can be served",
          "minLength": 1
        },
        "registered_agent_name": {
          "type": ["string","null"],
          "description": "The 'Agent' of the company \u2013 a person or entity that is empowered to accept service for the company",
          "minLength": 1
        },
        "number_of_employees": {
          "anyOf": [
            {"type":"string","minLength": 1},
            {"type":"number","minimum": 0}
          ],
          "description": "The number of employees"
        },
        "merged_into": {
          "type": "object",
          "description": "Information on the merger of this company into a 'survivor' company",
          "properties": {
            "surviving_company": {
              "type": ["object"],
              "description": "the surviving_company that this has been merged into",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "The legal name of the surviving company",
                  "minLength": 1
                },
                "company_number": {
                  "type": "string",
                  "description": "The company_number of the surviving company, if known",
                  "minLength": 1
                },
                "jurisdiction": {
                  "type": "string",
                  "description": "The jurisdiction of incorporation of the surviving company",
                  "minLength": 2
                }
              },
              "anyOf": [{"required": ["name"]},
                        {"required": ["company_number"]}]
            },
            "effective_date": {
              "type": "string",
              "format": "date",
              "description": "The date of the merger"
            }
          },
          "additionalProperties": false,
          "required": ["surviving_company"]
        }
      }
    }
  },
  "additionalProperties": false,
  "required": ["company_number", "name", "jurisdiction_code"]
}

=== openc/openc-schema/spec/sample-data/valid/company-09.json
{
  "name": "Foo Inc",
  "company_number": "12345",
  "jurisdiction_code": "ie",
  "previous_names": [
    {
      "company_name": "FooBar Inc"
    },
    {
      "company_name": "FooBaz",
      "con_date": "2012-07-22"
    },
    {
      "company_name": "FooBaz",
      "con_date": "2012-07-22",
      "start_date": "2008-01-08"
    }
  ]
}

=== openc/openc-schema/spec/sample-data/valid/company-33.json
{
  "name": "Foo Inc",
  "company_number": "12345",
  "jurisdiction_code": "ie",
  "industry_codes": [
    {
      "code": "1234",
      "code_scheme_id": "eu_nace_2",
      "name": "Some Industry"
    },
    {
      "code": "1234",
      "code_scheme_id": "unknown_code_scheme",
      "name": "Some Industry"
    },
    {
      "code": "22.11",
      "code_scheme_id": "uk_sic_2007"
    },
    {
      "code": "43.21",
      "code_scheme_id": "us_naics_2007",
      "name": "Another Industry",
      "start_date": "2010-12-22",
      "end_date": "2011-01-03"
    }
  ]
}
