=== openc/openc-schema/schemas/licence-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "A Licence is a permission for an entity to do something that would otherwise not be permitted. Note that such permissions are recorded in multiple different ways and to different granularity. In addition categories cross over, for example a pawnborker may be regulated as a retail establishment by a city, but also as a financial institution by a national or regional financial regulator. Sometimes the licence is a simple statement â€“ the government of Rwanda has given a banking licence to a certain bank -- other times it is fine-grained and highly complex (e.g. an extractives licence or the UK FCA licencing scheme). This schema tries to make it easy to submit the former, while not losing granularity of the latter. The object has the name of Rich Licence to distinguish it from Simple Licence, which it is expected to ultimately replace.",
  "properties": {
    "licence_holder": {
      "properties": {
        "entity": {
          "oneOf": [
            {
              "properties": {
                "entity_type": {
                  "enum": [
                    "company"
                  ]
                },
                "entity_properties": {
                  "$ref": "basic-company-schema.json"
                }
              }
            },
            {
              "properties": {
                "entity_type": {
                  "enum": [
                    "person"
                  ]
                },
                "entity_properties": {
                  "$ref": "includes/person.json"
                }
              }
            },
            {
              "properties": {
                "entity_type": {
                  "enum": [
                    "organisation"
                  ]
                },
                "entity_properties": {
                  "$ref": "includes/organisation.json"
                }
              }
            },
            {
              "properties": {
                "entity_type": {
                  "enum": [
                    "unknown"
                  ]
                },
                "entity_properties": {
                  "$ref": "includes/unknown_entity_type.json"
                }
              }
            }
          ]
        },
        "entity_type": {
          "enum": [
            "company",
            "person",
            "organisation",
            "unknown_entity_type",
            null
          ]
        }
      }
    },
    "licence_issuer": {
      "oneOf": [
        {
          "type": [
            "string",
            "null"
          ],
          "minLength": 2
        },
        {
          "$ref": "includes/organisation.json"
        }
      ]
    },
    "licenced_location": {
      "$ref": "includes/address.json"
    },
    "licence_number": {
      "type": "string"
    },
    "start_date": {
      "description": "The issue date of the licence",
      "type": "string",
      "format": "date"
    },
    "end_date": {
      "description": "The expiry date of the licence",
      "type": "string",
      "format": "date"
    },
    "source_url": {
      "description": "Place where this fact can be verified",
      "type": "string",
      "minLength": 1
    },
    "confidence": {
      "description": "Confidence in accuracy of data",
      "type": "string",
      "enum": [
        "HIGH",
        "MEDIUM",
        "LOW"
      ]
    },
    "renewal_date": {
      "type": "string",
      "format": "date"
    },
    "sample_date": {
      "description": "Date on which we know this to be true (usually date this information was retrieved from the source)",
      "type": "string",
      "format": "date"
    },
    "licence_url": {
      "type": "string",
      "description": "A public URL for the licence"
    },
    "jurisdiction_of_licence": {
      "type": "string",
      "description": "The area in which this licence is valid"
    },
    "status": {
      "type": "string",
      "description": "The status of the licence. If the licence is made up of a number of permissions, each of which has a status, store the status in the permissions field instead/as well"
    },
    "category": {
      "description": "Category of licence",
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Financial",
          "Business",
          "Extractive"
        ]
      }
    },
    "permissions": {
      "type": "array",
      "items": {
        "$ref": "includes/permission.json"
      }
    },
    "other_attributes": {
      "description": "Use for other licence attributes for which we don't yet have curated schema attributes",
      "type": "object"
    }
  },
  "additionalProperties": false,
  "required": [
    "source_url",
    "sample_date",
    "licence_holder",
    "permissions",
    "licence_issuer",
    "jurisdiction_of_licence"
  ]
}

=== openc/openc-schema/spec/sample-data/valid/rich-licence-02.json
{
    "confidence": "HIGH",
    "licence_holder": {
        "entity": {
            "entity_type": "company",
            "entity_properties": {
                "name": "MEZA  ALFREDO T",
		"company_number": "ZZZ95",
                "jurisdiction_code": "us_ca"
            }
        }
    },
    "licence_issuer": {
        "jurisdiction": "us_ca",
        "name": "California Alcoholic Beverage Control"
    },
    "licence_number": "00100196",
    "other_attributes": {
        "district_office_code": "08",
        "duplicate_counts": "",
        "fee_codes": "P40",
        "geo_code": "3309",
        "master_indicator": "Y",
        "premise_census_tract": "0455.02",
        "premise_county": "RIVERSIDE",
        "term_in_months": "12"
    },
    "jurisdiction_of_licence": "us_ca",
    "permissions": [
        {
            "activity_name": "Off-Sale Beer and Wine",
            "permission_type": "operating"
        }
    ],
    "sample_date": "2015-01-05",
    "source_url": "http://www.abc.ca.gov/datport/DataExport.html",
    "start_date": "1981-01-21",
    "end_date": "2015-06-30",
    "status": "ACTIVE"
}

=== openc/openc-schema/spec/sample-data/valid/licence-04.json
{
    "confidence": "HIGH",
    "end_date": "2017-02-28",
    "licence_holder": {
        "entity_properties": {
            "jurisdiction": "FL",
            "name": "GLB DESIGN GROUP, LLC"
        },
        "entity_type": "company"
    },
    "licence_issuer": {
        "jurisdiction": "us_fl",
        "name": "Florida Architecture & Interior Design Board"
    },
    "licence_number": "26001644",
    "other_attributes": {
        "Alternate Lic#": "IB26001644",
        "Blank": "",
        "County Code": "23",
        "Effective Date": "2014-12-22",
        "Primary Status": "C",
        "Renewal Period": "",
        "Secondary Status": "A"
    },
    "permissions": [
        {
            "activity_name": "Interior Design Business",
            "permission_type": "operating"
        }
    ],
    "sample_date": "2014-12-31 11:46:08 +0000",
    "source_url": "ftp://dbprftp.state.fl.us/pub/llweb/lic02ai.csv",
    "jurisdiction_of_licence": "us_fl",
    "start_date": "2014-12-22",
    "status": "Active (Current)"
}
