=== openc/openc-schema/schemas/official-register-entry-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "An official register entry is a record of an entity being on an official register, for example a charity register, register of minority owned businesses, or an official list of government contractors, etc -- Q could there be multiple register entries per registration ... how do we cope with this",
  "properties": {
    "registrant": {
      "$ref": "includes/entity.json"
    },
    "register": {
      "register_name": {
        "type": "string"
      },
      "register_type": {
        "type": "string",
        "enum": ["nonprofit","disadvantaged_business","government_contactor"]
      },
      "identifier_code_system": {
        "description": "If the register uses a recognised code system - e.g. tax numbers as unique identifiers â€“ list this identifier code system here, e.g. us_fein (US Federal tax number). See identifier schema for details",
        "type": ["string", null]
      },
      "managing_organisation": {
        "$ref": "includes/organisation.json"
      }
    },
    "register_uid": {
      "type": "string",
      "description": "the unique identifier on the register"
    },
    "start_date": {
      "description": "The date the entity was registered",
      "type": "string",
      "format": "date"
    },
    "end_date": {
      "description": "The date the entity was de-registered",
      "type": "string",
      "format": "date"
    },
    "source_url": {
      "description": "Place where this fact can be verified",
      "type": "string",
      "minLength": 1
    },
    "confidence": {
      "description": "Confidence in accuracy of data",
      "type": "string",
      "enum": [
        "HIGH",
        "MEDIUM",
        "LOW"
      ]
    },
    "sample_date": {
      "description": "Date on which we know this to be true (usually date this information was retrieved from the source)",
      "type": "string",
      "format": "date"
    },
    "retrieved_at": {
      "description": "Date-time this was retrieved from the source",
      "type": "string",
      "format": "date"
    },
    "register_entry_url": {
      "type": "string",
      "description": "A public URL for the register entry"
    },
    "status": {
      "type": "string",
      "description": "The status of the register entry"
    },
    "permissions": {
      "type": "array",
      "items": {
        "$ref": "includes/permission.json"
      }
    },
    "other_attributes": {
      "description": "Use for other register entry attributes for which we don't yet have curated schema attributes",
      "type": "object"
    }
  },
  "additionalProperties": false,
  "required": [
    "source_url",
    "sample_date",
    "registrant",
    "register"
  ]
}

=== openc/openc-schema/spec/sample-data/valid/official-register-entry-04.json
{
  "confidence": "HIGH",
  "registrant": {
    "entity_type": "company",
    "entity_properties": {
      "alternative_names": [
        {
          "company_name": "CHUCK E. CHEESE'S",
          "type": "trading"
        }
      ],
      "jurisdiction_code": "us_ny",
      "name": "CEC ENTERTAINMENT, INC.",
      "telephone_number": "(972) 258-5807",
      "identifiers": [
        {
          "uid": "12345",
          "identifier_system_code": "us_rssd"
        }
      ]
    }
  },
  "register": {
    "jurisdiction": "United States",
    "name": "FDIC Institution Directory",
    "identifier_code_system": "us_fdic",
    "managing_organisation": {
      "name": "US Federal Deposit Insurance Corporation",
      "jurisdiction": "us",
      "website": "http://www2.fdic.gov"
    }

  },
  "register_uid": "1141789",
  "register_entry_url": "http://www2.fdic.gov/idasp/confirmation.asp?inCert1=1141789",
  "other_attributes": {
    "address_location": "1 FL",
    "borough": "Bronx"
  },
  "sample_date": "2014-12-09",
  "source_url": "http://www2.fdic.gov/idasp/"
}

=== openc/openc-schema/spec/sample-data/valid/official-register-entry-03.json
{
  "confidence": "HIGH",
  "registrant": {
    "entity_type": "company",
    "entity_properties": {
      "alternative_names": [
        {
          "company_name": "AIA",
          "type": "abbreviation"
        }
      ],
      "jurisdiction_code": "gb",
      "company_number": "1234",
      "name": "ASSOCIATION FOR INDUSTRIAL ARCHAEOLOGY",
      "telephone_number": "01224 732558",
      "website": "http://www.industrial-archaeology.org.uk",
      "officers": [
        {"name": "John Smith", "position": "trustee"}
      ]
    }
  },
  "register": {
    "jurisdiction": "England & Wales",
    "name": "Charity Register of England & Wales",
    "register_type": "nonprofit",
    "identifier_code_system": "gb_ew_cc",
    "managing_organisation": {
      "name": "Charity Commission of England & Wales",
      "jurisdiction": "gb_ew",
      "website": "http://www.charitycommission.gov.uk"
    }
  },
  "register_uid": "277511",
  "other_attributes": {
    "activities": [
      "THE AIA IS THE NATIONAL ORGANISATION FOR PEOPLE WHO SHARE AN INTEREST IN BRITAIN'S INDUSTRIAL PAST. IT BRINGS TOGETHER PEOPLE WHO ARE RESEARCHING, RECORDING, PRESERVING AND PRESENTING THE GREAT VARIETY OF THIS COUNTRY'S INDUSTRIAL HERITAGE."
    ]
  },
  "sample_date": "2014-12-09",
  "source_url": "https://data.cityofnewyork.us/Business/foo_bar"
}

=== openc/openc-schema/spec/sample-data/valid/official-register-entry-01.json
{
  "confidence": "HIGH",
  "registrant": {
    "entity_type": "company",
    "entity_properties": {
      "alternative_names": [
        {
          "company_name": "CHUCK E. CHEESE'S",
          "type": "trading"
        }
      ],
      "jurisdiction_code": "us_ny",
      "name": "CEC ENTERTAINMENT, INC.",
      "telephone_number": "(972) 258-5807"
    }
  },
  "register": {
    "jurisdiction": "New York City",
    "name": "New York City Department of Consumer Affairs"
  },
  "register_uid": "1141789",
  "other_attributes": {
    "address_location": "1 FL",
    "borough": "Bronx"
  },
  "permissions": [
    {
      "activity_name": "Amusement Arcade",
      "permission_type": "operating"
    }
  ],
  "sample_date": "2014-12-09",
  "source_url": "https://data.cityofnewyork.us/Business/foo_bar"
}
