=== openc/openc-schema/schemas/simple-subsidiary-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "source_url": {
      "description": "Place where this fact can be verified",
      "type": "string",
      "minLength": 1
    },
    "sample_date": {
      "description": "Date on which this fact was known to be true",
      "type": "string",
      "format": "date"
    },
    "start_date": {
      "description": "Earliest known date this was known to be a subsidiary",
      "type": "string",
      "format": "date"
    },
    "end_date": {
      "description": "Latest known date this was known to be a subsidiary",
      "type": "string",
      "format": "date"
    },
    "confidence": {
      "description": "Confidence in accuracy of data",
      "type": "string",
      "enum": [
        "HIGH",
        "MEDIUM",
        "LOW"
      ]
    },
    "retrieved_at": {
      "type": "string",
      "format": "date"
    },
    "parent_name": {
      "description": "Name of the controlling company",
      "type": "string",
      "minLength": 1
    },
    "parent_jurisdiction": {
      "description": "Jurisdiction where controlling company is based",
      "type": "string",
      "minLength": 1
    },
    "parent_identifier": {
      "description": "Any unique ID for the controlling company",
      "type": "string"
    },
    "direct": {
      "description": "Is the control relationship direct or indirect (if unknown, leave blank)?",
      "type": "boolean"
    },
    "percentage_controlled": {
      "description": "Percentage of the subsidiary that is controlled (if known), either directly or indirectly",
      "type": "string",
      "pattern": "^[0-9]{1,2}0?[.]?[0-9]{0,2}$"
    },
    "subsidiary_name": {
      "description": "The name of the subsidiary",
      "type": "string",
      "minLength": 1
    },
    "subsidiary_jurisdiction": {
      "description": "Jurisdiction of the subsidiary",
      "type": "string",
      "minLength": 1
    },
    "subsidiary_identifier": {
      "description": "Any unique id for the subsidiary that might be provided in the source",
      "type": "string"
    }
  },
  "other_attributes": {
    "description": "Use for other attributes for which we don't yet have curated schema attributes",
    "type": "object"
  },
  "additionalProperties": false,
  "required": [
    "source_url",
    "sample_date",
    "parent_name",
    "parent_jurisdiction",
    "subsidiary_name",
    "subsidiary_jurisdiction"
  ]
}

=== openc/openc-schema/spec/sample-data/valid/simple-subsidiary-02.json
{
  "source_url": "http://somewhere.com/a",
  "sample_date": "2014-02-01",
  "start_date": "2014-01-01",
  "end_date": "2015-02-01",
  "confidence": "HIGH",
  "parent_name": "Widgets R US",
  "parent_jurisdiction": "us_de",
  "direct": true,
  "percentage_controlled": "56",
  "subsidiary_name": "Little Widgets",
  "subsidiary_jurisdiction": "us_de"
}
