=== openc/openc-schema/schemas/subsidiary-relationship-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "A relationship of control between two companies",
  "type": "object",
  "properties": {
    "sample_date": {
      "type": "string",
      "format": "date"
    },
    "start_date": {
      "type": "string",
      "format": "date"
    },
    "start_date_type": {
      "type": "string"
    },
    "end_date": {
      "type": "string",
      "format": "date"
    },
    "end_date_type": {
      "type": "string"
    },
    "retrieved_at": {
      "type": "string",
      "format": "date"
    },
    "source_jurisdiction": {
      "description": "Jurisdiction of the source of the data",
      "type": "string"
    },
    "company": {
      "$ref": "includes/company.json"
    },
    "data": {
      "type": "array",
      "description": "This is an array of data objects, that is the objects which actually contain the data about the datum. Generally there will only be one element in this, although in for some types of data_types there may naturally be several releated to the same company, e.g. shareholders",
      "items": {
        "$ref": "includes/subsidiary-relationship-data.json"
      },
      "additionalItems": false
    }
  },
  "additionalProperties": false,
  "required": [
    "company",
    "data",
    "sample_date"
  ]
}

=== openc/openc-schema/spec/sample-data/valid/subsidiary-relationship-01.json
{
  "company": {
    "name": "BP Europa SE",
    "jurisdiction": "Spain"
  },
  "sample_date": "2014-02-01",
  "start_date": "2013-07-06",
  "start_date_type": "before",
  "data": [
    {
      "data_type": "subsidiary_relationship",
      "confidence": 80,
      "source_url": "https://docs.google.com/file/d/0B5ORBm2amqZSY2NvOFQwbTZvemM",
      "properties": {
        "direct": true,
        "percentage_controlled": "100",
        "subsidiary": {
          "name": "\"TSG Polska\" Spolka z ograniczona odpowiedzialnocia",
          "jurisdiction": "Poland"
        }
      }
    }
  ]
}
